#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#
# IMPORTANT: this project ships WITHOUT gradle/wrapper/gradle-wrapper.jar
# (see docs/BUILD_REPORT.md — the generation environment had no network
# access to download it). CI does not depend on this script; the GitHub
# Actions workflow provisions Gradle 8.7 directly. To use this script
# locally, first run `gradle wrapper --gradle-version 8.7` once with a
# system-installed Gradle to regenerate gradle-wrapper.jar, or run
# `gradle <task>` directly if you have Gradle 8.7 installed.
#

APP_HOME=$(cd "$(dirname "$0")" && pwd -P)
APP_NAME="Gradle"
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
  echo "ERROR: $CLASSPATH not found."
  echo "This source drop does not include the wrapper jar binary (no network access at generation time)."
  echo "Install Gradle 8.7 and run: gradle wrapper --gradle-version 8.7"
  echo "Then re-run ./gradlew, or just use 'gradle' directly for this task."
  exit 1
fi

if [ -n "$JAVA_HOME" ] ; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD="java"
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  "-Dorg.gradle.appname=$APP_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
